-- MySQL Script generated by MySQL Workbench
-- 11/23/16 05:44:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aulasreserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aulasreserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aulasreserva` DEFAULT CHARACTER SET utf8 ;
USE `aulasreserva` ;

-- -----------------------------------------------------
-- Table `aulasreserva`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulasreserva`.`aula` (
  `idaula` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL,
  `piso` VARCHAR(2) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `caracteristicas` VARCHAR(512) NULL,
  `estado` VARCHAR(15) NOT NULL,
  `tipo_aula` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idaula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aulasreserva`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulasreserva`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apaterno` VARCHAR(20) NOT NULL,
  `amaterno` VARCHAR(20) NOT NULL,
  `tipo_documento` VARCHAR(15) NOT NULL,
  `num_documento` VARCHAR(8) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` VARCHAR(9) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aulasreserva`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulasreserva`.`solicitante` (
  `idpersona` INT NOT NULL,
  `codigo_solicitante` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `codigo_solicitante_UNIQUE` (`codigo_solicitante` ASC),
  CONSTRAINT `fk_persona_solicitante`
    FOREIGN KEY (`idpersona`)
    REFERENCES `aulasreserva`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aulasreserva`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulasreserva`.`trabajador` (
  `idpersona` INT NOT NULL,
  `sueldo` DECIMAL(6,2) NOT NULL,
  `acceso` VARCHAR(15) NOT NULL,
  `login` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_persona_trabajador`
    FOREIGN KEY (`idpersona`)
    REFERENCES `aulasreserva`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aulasreserva`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulasreserva`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `idaula` INT NOT NULL,
  `idsolicitante` INT NOT NULL,
  `idtrabajador` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_aula_idx` (`idaula` ASC),
  INDEX `fk_reserva_solicitante_idx` (`idsolicitante` ASC),
  INDEX `fk_reserva_trabajador_idx` (`idtrabajador` ASC),
  CONSTRAINT `fk_reserva_aula`
    FOREIGN KEY (`idaula`)
    REFERENCES `aulasreserva`.`aula` (`idaula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_solicitante`
    FOREIGN KEY (`idsolicitante`)
    REFERENCES `aulasreserva`.`solicitante` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_trabajador`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `aulasreserva`.`trabajador` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
